### ISSUE TITLE
In AArch64 mode, the register should be 64bit

### ISSUE THREAD

**Issue by Proteas** [hugsy/cemu#10]
asm:
`mov x1, #0x1234
add x1, x0, x1, lsl #24`
Currently, it only displays the lower 32 bit.

Thank you for the project.

**Comment by hugsy** [comment]
My bad, aarch64 was returning a memory alignment of 32bits. This is fixed. Please try again and close the bug if fixed.

Cheers

**Comment by Proteas** [comment]
Yes, the function is right now.
but, should adjust the UI because 64 bit is too long to display: "0x0000001234000..."
