### ISSUE TITLE
Switch to arm architecture and run error:[ERROR] __generate_text_bytecode() failed

### ISSUE THREAD

**Issue by DenkoWu** [hugsy/cemu#105]
* [ ] Did you use the latest version of CEMU from `dev` branch?
* [ ] Did you check [current and past issues](https://github.com/hugsy/cemu/issues)?
* [ ] Did you check [current and past PR](https://github.com/hugsy/cemu/pulls)?

### Step 1: Describe your environment

Operating System / Distribution: Windows 11 64-bit
Python version:  3.10.4
CEMU version (installed from pip, git etc.): 0.8

#### Steps to reproduce

1.
<img width="1189" alt="微信图片_20240923005753" src="https://github.com/user-attachments/assets/a99d5014-24b0-41ea-bebf-5134e02857f3">

Switch to arm architecture and run error 

#### Observed Results

* What happened? This could be a description, log output, etc.

[ERROR] Failed to compile: exception KsError: Unknown token in expression (KS_ERR_ASM_EXPR_TOKEN)
[ERROR] __generate_text_bytecode() failed
[INFO] Emulator is now RUNNING
[INFO] Running all from 0x4000 to 0x4000
[INFO] Emulator is now FINISHED

**Comment by hugsy** [comment]
Your syntax is invalid (valid -> `mov r0, 100`)
![image](https://github.com/user-attachments/assets/db161e8e-883e-4509-971e-8aa07d02c636)
