### ISSUE TITLE
Missing mem_unmap function in python 2.7 (32bit)

### ISSUE THREAD

**Issue by computerline1z** [hugsy/cemu#11]
I see the function mem_unmap is missing from http://www.unicorn-engine.org/download/ setup package, does any way to replace it, or must build with the newest repo ?

https://github.com/hugsy/cemu/blob/master/cemu/emulator.py#L226

**Comment by hugsy** [comment]
That's an issue related to unicorn not cemu. 
Try again with the latest version of unicorn, if you have an issue drop them an issue.

Thanks

**Comment by computerline1z** [comment]
Thanks you :) Seem must rebuild unicorn. Thanks for great app !

**Comment by hugsy** [comment]
Glad you liked !

Closing the issue.
