### ISSUE TITLE
python-qt5 installation issue

### ISSUE THREAD

**Issue by GelosSnake** [hugsy/cemu#13]
Getting this when running requirements.sh on latest osx:
Collecting python-qt5
  Downloading python-qt5-0.1.10.zip (57.5MB)
    100% |████████████████████████████████| 57.5MB 24kB/s 
No files/directories in /private/tmp/pip-build-It5nVa/python-qt5/pip-egg-info (from PKG-INFO)

any idea?

**Comment by Proteas** [comment]
python-qt5 is a Win distribution.
you could install PyQt5 on macOS according to this link: https://gist.github.com/vityafx/e01ab56d28a2c9467cc6
I use the Qt5.4.1, and cemu is working fine.

**Comment by hugsy** [comment]
@Proteas I'm not a big OSX user myself but I did my tests on OSX 10.10 and a simple 
```
$ brew install pyqt5
```
worked like a charm.
