### ISSUE TITLE
Error: cannot stop, cannot emulate instructions separately

### ISSUE THREAD

**Issue by trietptm** [hugsy/cemu#16]
Hi, I'm using cemu in Windows x64 with Python 2.7 x64, I cannot execute instructions one-by-one (separately) and after click "Next instruction", I see all instructions are executed and I cannot click "Stop".

> QObject::connect: Cannot queue arguments of type 'QTextBlock'
> (Make sure 'QTextBlock' is registered using qRegisterMetaType().)
> QObject::connect: Cannot queue arguments of type 'QTextCursor'
> (Make sure 'QTextCursor' is registered using qRegisterMetaType().)
> QObject::connect: Cannot queue arguments of type 'QTextCursor'
> (Make sure 'QTextCursor' is registered using qRegisterMetaType().)
> Traceback (most recent call last):
>   File "D:\GitHub\cemu\cemu\core.py", line 511, in stopCode
>     self.emu.stop()
>   File "D:\GitHub\cemu\cemu\emulator.py", line 226, in stop
>     self.vm.mem_unmap(addr, size)
> AttributeError: 'Uc' object has no attribute 'mem_unmap'

![screenshot - 9_25_2016 8_28_10 pm](https://cloud.githubusercontent.com/assets/526959/18815522/a84c4092-835e-11e6-8964-d54bf8084d96.png)

**Comment by hugsy** [comment]
By the look of your stack trace, I would say that your issue comes from your Unicorn engine version and/or installation. You might want to check those out.

**Comment by trietptm** [comment]
@hugsy , I installed Unicorn from https://github.com/unicorn-engine/unicorn/releases/download/0.9/unicorn-0.9-python2.7-win32.exe .
Which release of Unicorn do you recommend to install?

**Comment by hugsy** [comment]
I've tested `cemu` with the latest packages from `keystone`, `capstone` and `unicorn` and it works perfectly well: 

![](https://i.imgur.com/gaC1m6X.png)

This issue was probably originating from an old version of Unicorn, doesn't apply any longer.
Closing this issue.
