### ISSUE TITLE
Missing required dependency 'unicorn'

### ISSUE THREAD

**Issue by CryptXor** [hugsy/cemu#18]
So I have build and installed capstone/unicorn/keystone/pyqt/pygments/etc/etc/etc.
However I keep getting this issue, but the bindings are definitely installed
```
E:\Applications\cemu>python main.py
[-] Missing required dependency 'unicorn'
```

Unicorn
```
E:\Applications\cemu>pip install capstone
Requirement already satisfied (use --upgrade to upgrade): capstone in c:\python\lib\site-packages

E:\Applications\cemu>pip install keystone
Requirement already satisfied (use --upgrade to upgrade): keystone in c:\python\lib\site-packages

E:\Applications\cemu>easy_install unicorn
Searching for unicorn
Best match: unicorn 1.0
Processing unicorn-1.0-py3.5.egg
unicorn 1.0 is already the active version in easy-install.pth

Using c:\python\lib\site-packages\unicorn-1.0-py3.5.egg
Processing dependencies for unicorn
Finished processing dependencies for unicorn

E:\Applications\cemu>python main.py
[-] Missing required dependency 'unicorn'
```

Python35 x64 Windows 10 Pro

**Comment by hugsy** [comment]
This seems to be a problem with your installation of the requirements, not `cemu` itself. Make sure that you have all modules running for your correct version of Python.

**Comment by CryptXor** [comment]
It would appear to be an issue with unicorn and the python 3 bindings compatibility. I assume you run cemu with python 2.7 on windows?

**Comment by hugsy** [comment]
Correct, I only have tested on Win10 and Python2.7 32bit.
If it's really too painful to get `unicorn-engine` on your configuration, you can use a Linux VM and run the shell script to install the dependencies for you. `cemu` was originally made for / on Linux.
