### ISSUE TITLE
unbuildable project?

### ISSUE THREAD

**Issue by srozb** [hugsy/cemu#2]
keystone-engine readme states:

> Keystone will be released to public after a testing phase

is it possible to build cemu in spite of this fact? If so, how?

**Comment by hugsy** [comment]
I'm sorry but no, `cemu` heavily relies on `keystone`. It is not available to the public because it is being tested right now.
But you can get access to the private release of `keystone` by contacting its author. He is very friendly and probably let you access it too.

Thanks.

**Comment by srozb** [comment]
thank you
