### ISSUE TITLE
requirements.sh

### ISSUE THREAD

**Issue by CryptXor** [hugsy/cemu#20]
There is a small bug in requirements.sh; after building and installing keystone `sudo ldconfig` needs to be run (at least on debian) I would submit a pull request, but that is a little tricky when you are on your phone :rofl:

**Comment by hugsy** [comment]
I don't why `ldconfig` should be run for keystone Python bindings to be installed. I'm using Debian as both host and in VM for testing, never had to run `ldconfig` for `cemu` to work.

**Comment by CryptXor** [comment]
If you don't then keystone will keep throwing a "library not found" error if it is installed into a */lib folder that the system links too. The problem being that keystone builds and installs shared libraries, but the system cache hasn't loaded the new libraries, so python will spit out the "library not found" error consistently :)

**Comment by hugsy** [comment]
Commit 6b1fa47
