### ISSUE TITLE
rep instructions cause compile error

### ISSUE THREAD

**Issue by CeruleanSky** [hugsy/cemu#21]
base64 of raw program:

```i30Ii9czwIPJ//Kug8EC99mKRQyL+vOqi8I=```

which is originally: 

8B 7D 08 mov edi, [ebp+8]  
8B D7 mov edx, edi  
33 C0 xor eax, eax  
83 C9 FF or ecx, 0FFFFFFFFh  
F2 AE repne scasb  
83 C1 02 add ecx, 2  
F7 D9 neg ecx  
8A 45 0C mov al, [ebp+0Ch]  
8B FA mov edi, edx  
F3 AA rep stosb  
8B C2 mov eax, edx  

and disassembles in capstone as:     

mov edi, dword ptr [ebp + 8]
mov edx, edi
xor eax, eax
or ecx, 0xffffffff
repne scasb al, byte ptr es:[edi]
add ecx, 2
neg ecx
mov al, byte ptr [ebp + 0xc]
mov edi, edx
rep stosb byte ptr es:[edi], al
mov eax, edx

But comes out as a byte array after being assembled in keystone  code, cnt = ks.asm(original_code) as:  

bytearray(b'\x8b}\x08\x89\xfa1\xc0\x83\xc9\xff\xf2\xae\x83\xc1\x02\xf7\xd9\x8aE\x0c\x89\xd7\xf3\xaa\x89\xd0') and a count of 14.

This causes [self.num_insns != n and a compile error](https://github.com/hugsy/cemu/blob/master/cemu/emulator.py#L159), though it was perfectly assembled by keystone.

Commenting out the rep/repne instructions reveals they are causing the imbalance in the number of instructions before and after.

I'm sure there are other instructions with the same issue, but fixing this problem will likely fix them also, and I would suppose there are deeper problems than just fixing the count, as instruction imbalances or repeating an instruction might cause issues with stepping.

**Comment by hugsy** [comment]
Hi, thanks for reporting the issue.
It should be fixed, only displaying is sufficient for this case as `cemu` will stop anyway if the assembling step fails.

Let me know.

Cheers.
