### ISSUE TITLE
Where did you get keystone?

### ISSUE THREAD

**Issue by movEAX** [hugsy/cemu#3]
As I know, it's not published yet.

**Comment by hugsy** [comment]
It has been published privately for testing a few weeks ago. You can participate by sending an email to Quynh (see Keystone page for that) or wait a few weeks for it to be publicly released.

Cheers

**Comment by DigiAngel** [comment]
Heh...kills my testing for today...thanks.

**Comment by yformaggio** [comment]
Keystone is available to public since today :+1:

**Comment by hugsy** [comment]
https://github.com/keystone-engine/keystone

Enjoy !
