### ISSUE TITLE
Can't Assemble x86-64

### ISSUE THREAD

**Issue by bdemick** [hugsy/cemu#32]
Getting a very odd issue trying to run a single test instruction post cemu installation. Log below. What's odd is that this works fine on my VMWare VM, but on my VirtualBox machine, built from the exact same script, stubbornly refuses to assemble x64 in cemu. kstool seems to handle this instruction just fine, so it doesn't appear to be an issue with the Keystone build. Any thoughts? Start over from scratch?

    Switching to 'Intel i386 64bit, syntax Intel - little endian'  
    [logger] Setup - Map .text @40000 (size=4096,perm=READ|EXEC)  
    [logger] Setup - Map .data @60000 (size=4096,perm=READ|WRITE)  
    [logger] Setup - Map .stack @800000 (size=16384,perm=READ|WRITE)  
    [logger] Setup - Map .misc @900000 (size=4096,perm=ALL)  
    [logger] Compilation - Assembling 1 instructions for Intel i386 64bit:  
    b'mov rsi, 3'  
    [logger] Error - Failed to compile code  
    An error occured when loading context

**Comment by hugsy** [comment]
What if you try to assemble directly from the Python interpreter?

**Comment by bdemick** [comment]
Works fine from Python3 (at least for the test example):

```
from keystone import *

# separate assembly instructions by ; or \n
CODE = b"mov rdi, 2"
 
try:
      # Initialize engine in X86-32bit mode
      ks = Ks(KS_ARCH_X86, KS_MODE_64)
      encoding, count = ks.asm(CODE)
      print("%s = %s (number of statements: %u)" %(CODE, encoding, count))
except KsError as e:
      print("ERROR: %s" %e)
```
emits `b'mov rdi, 2' = [72, 199, 199, 2, 0, 0, 0] (number of statements: 1)` which looks right.

**Comment by hugsy** [comment]
Are you using the latest from `master` or the PIP version? On `master`, your error message should look like 
```
[logger] Error - Failed to compile: error at line 1
```

**Comment by bdemick** [comment]
PIP version.

**Comment by hugsy** [comment]
Can you upgrade to the `master` ?

**Comment by hugsy** [comment]
Glad to know. I will release the current `master` as 0.2.2 very soon.

Cheers
