### ISSUE TITLE
Missing required dependency 'keystone'

### ISSUE THREAD

**Issue by seekM** [hugsy/cemu#36]
I'm using Ubuntu 18.04.1 LTS. I installed `cemu` via `pip3 install cemu`:

> Collecting cemu
>   [...] Downloading [...] 
> Building wheels for collected packages: cemu, capstone, keystone-engine
>   Running setup.py bdist_wheel for cemu ... done
>   Stored in directory: /home/user/.cache/pip/wheels/1d/61/92/73c06d1d4e50395016232fe2d1190d507e9e301f1aa5c0563a
>   Running setup.py bdist_wheel for capstone ... done
>   Stored in directory: /home/user/.cache/pip/wheels/6b/94/22/74a96ea9b9b5af3c506f45d5062aeac4ec5dae2ac1bfc59d9b
>   Running setup.py bdist_wheel for keystone-engine ... done
>   Stored in directory: /home/user/.cache/pip/wheels/e9/40/c1/6ac6e82d6aa880cd8d492d95e59be376eb77015683b94ee934
> Successfully built cemu capstone keystone-engine
> Installing collected packages: PyQt5-sip, PyQt5, Pygments, capstone, keystone-engine, unicorn, cemu
> Successfully installed PyQt5-5.11.2 PyQt5-sip-4.19.12 Pygments-2.2.0 capstone-3.0.5 cemu-0.2.2 keystone-engine-0.9.1.post3 unicorn-1.0.1

([full log](https://pastebin.com/8QSq5Rbr))

When I start `cemu` afterwards I get the following error:

> [-] Missing required dependency 'keystone'

How can this be fixed?

**Comment by hugsy** [comment]
Might be this: https://github.com/hugsy/cemu#kali-linux

**Comment by seekM** [comment]
Thank for suggesting this, but unfortunately this did not help

**Comment by hugsy** [comment]
This is an installation issue, not a bug from Cemu.
I suggest you make sure that `keystone`, `unicorn` and `capstone` are running properly in a python interpreter. Cemu will work after that. 

Cheers

**Comment by hugsy** [comment]
Housekeeping
