### ISSUE TITLE
Running setup.py install for unicorn ... error

### ISSUE THREAD

**Issue by kajirashad** [hugsy/cemu#41]
<img width="1263" alt="screen shot 2019-01-06 at 1 29 05 pm" src="https://user-images.githubusercontent.com/18077252/50740061-1590a880-11b7-11e9-8c0d-5b190fb55039.png">

Getting the above error after successfully running `brew install capstone`. I manually checked and the error is correct, there isn't any pthread.h file in the 'Headers' folder nor is there a 'libunicorn.dylib' file in the 'lib' folder. Is this something I manually install then re-run the second command line instruction: `pip3 install -U cemu`?

**Comment by hugsy** [comment]
Closing because it's not related to CEmu. 

You might prefer compiling directly from the source code keystone, capstone and unicorn. They will be more up to date, and less prone to some packaging fu**ery.

Cheers,
