### ISSUE TITLE
OSX installation fails

### ISSUE THREAD

**Issue by RomainQuidet** [hugsy/cemu#42]
Hi
I tried to install following your readme on OSX 10.14.3 with homebrew configured (I'm an iOS dev).
Command pip3 install -U cemu fails compiling unicorn (qemu missing pthread).

Building wheel for unicorn (setup.py) ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_d/t7gfdbs16qdfzmzv7ry6q9fc0000gn/T/pip-install-_3nlbb5b/unicorn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/_d/t7gfdbs16qdfzmzv7ry6q9fc0000gn/T/pip-wheel-y1qsj0ve --python-tag cp37:
  running bdist_wheel
  running build
  Building C extensions
  cd qemu && \
  	./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden -m32 -arch i386 -m64 -arch x86_64" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"
  
  ERROR: pthread check failed
         Make sure to have the pthread libs and headers installed.
  
  make: *** [qemu/config-host.h-timestamp] Error 1
  error: [Errno 2] No such file or directory: 'libunicorn.dylib'
  
  ----------------------------------------
  Failed building wheel for unicorn

**Comment by hugsy** [comment]
Hi,

This is a problem with building unicorn, not `cemu`. That is where you should send an Issue.

And the issue is pretty obvious:
```
Make sure to have the pthread libs and headers installed
```

Cheers
