### ISSUE TITLE
Port CEMU to Python2

### ISSUE THREAD

**Issue by bdemick** [hugsy/cemu#5]
Got all the way to the end after much frustration with the PyQt5 dependency (without reading the source, of course!) and discovered that cemu requires Python 3.  Would be nice if the readme stated that, so people who tend to use older versions of Python don't make the same mistake I did and build PyQt5 for Python2.7.

**Comment by hugsy** [comment]
I will make it compatible with Python 2.

**Comment by bdemick** [comment]
Ah, I must have fat-fingered the apt-cache search.  Went straight to the developer website and they only showed wheel and source installation instructions.  Bad assumption on my part!

**Comment by hugsy** [comment]
`apt` based distro should find it easily:
```bash
$ apt search python3-pyqt5
```

However, since commit a702495 `cemu` should be working with Python2. Feel free to test it and report bugs.

Thanks

**Comment by bdemick** [comment]
Yep - typo'd my search, which cost me 3 hours of compile, break, fix deps, compile, break, repeat.  Just started testing your latest commit with Python2.7 on lubuntu, installing python-pyqt5, and looks golden so far.  Thanks for the quick port, this is a great tool!

**Comment by hugsy** [comment]
Glad you enjoy the tool!

Closing the issue.
