### ISSUE TITLE
Crash because newer keystone.asm does not have `as_bytes` arg

### ISSUE THREAD

**Issue by MarSoft** [hugsy/cemu#51]
```
Switching to 'ARM THUMB mode'                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                   
  File "/tmp/tmp.oUuaXwo2MV/lib/python3.8/site-packages/cemu/ui/codeeditor.py", line 80, in __update_assembly_code                                                                                                   
    code, cnt = assemble(asm, self.root.arch)                                                                                                                                                                        
  File "/tmp/tmp.oUuaXwo2MV/lib/python3.8/site-packages/cemu/utils.py", line 174, in assemble                                                                                                                        
    bytecode, cnt = ks.asm(asm_code, as_bytes=True)                                                                                                                                                                  
TypeError: asm() got an unexpected keyword argument 'as_bytes'                                                                                                                                                       
Segmentation fault
```

Installed versions: `cemu` - latest from the repo (rev 44427a8), `keystone-engine==0.9.1.post3`. Python version `3.8.0`.

Also, when I removed `as_bytes` kwarg in `cemu/utils.py`, it crashed with the different error:
```
Switching to 'ARM THUMB mode'                                                                             
Traceback (most recent call last):                                                                        
  File "/tmp/cemu/cemu/ui/codeeditor.py", line 81, in __update_assembly_code                              
    if len(code) > len(old_code):                                                                         
TypeError: object of type 'NoneType' has no len()                                                         
Segmentation fault
```
Looks like `Ks.asm` returns `None` for bytecode if no instructions were generated. But our code expects empty `bytes` instead.

**Comment by hugsy** [comment]
It looks like you use the old packaged version. Use this script

https://github.com/hugsy/stuff/blob/master/update-trinity.sh

to update unicorn, keystone and capstone and try again.

**Comment by Chrolive** [comment]
### Keystones python binding changed slightly here (as_bytes is added)
https://github.com/keystone-engine/keystone/pull/327
As a result the bindings as packaged are out of date. This may be fixed by running $python setup.py install 
this fixes the error on windows.

**Comment by hugsy** [comment]
Thanks for the bug tracking @Chrolive . Keystone from PyPi is [really not too date](https://pypi.org/project/keystone-engine/#history) that's why I tend to recommend to compile from scratch as a general line. 

This is not a from the tool, closing the issue.

**Comment by billythedummy** [comment]
> It looks like you use the old packaged version. Use this script
> 
> https://github.com/hugsy/stuff/blob/master/update-trinity.sh
> 
> to update unicorn, keystone and capstone and try again.

Did this but the same original error of unexpected_argument 'as_bytes' continued.



> ### Keystones python binding changed slightly here
> 
>     * [keystone-engine/keystone#327](https://github.com/keystone-engine/keystone/pull/327)
> 
> 
> As a result the bindings as packaged are out of date. This may be fixed by running
> 
>     1. (path-to-python) keystone/bindings/python/setup.py install
> 
> 
> this fixes the error on windows.

Tried this as well but did not work for Ubuntu 18.04
