### ISSUE TITLE
Cemu not display Registers with OSX Dark Mode

### ISSUE THREAD

**Issue by dark-lbp** [hugsy/cemu#52]
Cemu not display Registers with OSX Dark Mode

system: OSX 10.14.6

Light Mode
![image](https://user-images.githubusercontent.com/3477662/71143915-3252ae80-2257-11ea-9514-1e0ed392cc6e.png)

Dark Mode
![image](https://user-images.githubusercontent.com/3477662/71143964-5910e500-2257-11ea-8316-5ebfd7f354d5.png)

**Comment by dark-lbp** [comment]
Update PyQt5 from 5.11.2 to 5.13.2 didn’t fix the problem.

**Comment by hugsy** [comment]
I don't have an OSX so I won't address this.

Happy to merge a PR.

**Comment by hugsy** [comment]
House keeping.
