### ISSUE TITLE
Cemu IS NOT WORKING!

### ISSUE THREAD

**Issue by heyboiso** [hugsy/cemu#57]
This is a an issue that i reported but hugsy responded and said that is is written in python so its for 32bit and 64bit
BUT WHEN I LAUNCH IT IS SAYS THIS!

https://user-images.githubusercontent.com/70768242/99701766-93a18400-2a9d-11eb-9be0-dd050839ea0b.png

SO HUGSY DONT CLOSE THIS UNTIL U TELL ME WHAT IS HAPPENING OR HOW TO MAKE IT WORK!

Also dont say the solution and then close it bec i  will try it then if it works then close it

**Comment by hugsy** [comment]
Install Windows 10 x64 like everybody else.
