### ISSUE TITLE
Cannot run native ARM

### ISSUE THREAD

**Issue by sajidmc** [hugsy/cemu#59]
I am trying cEMU with OSX Catalina. Emulating any ARM code causes the program to be unresponsive, and I have to force quit it. Afterward, even x86 code execution causes the GUI to freeze. I suspect it might be an issue with one of the libraries. Is it possible to do a try-catch and avoid the crash?

**Comment by thanasions** [comment]
Same problem with me

**Comment by hugsy** [comment]
Not enough info, cleaning up
