### ISSUE TITLE
cemu crash when pushing 32 bit regs in  a 64 bit context

### ISSUE THREAD

**Issue by rb-x** [hugsy/cemu#64]
Hi, when we attempt to push a 32 bit register into the  stack in a 64 bit context :
```nasm
push eax
```
Considering the context, the instruction is invalid, but this cause the pyQT window to stop responding to, finally causing the program to crash.
(maybe an unhandled exception during assembling instruction with keystone ?)

**Comment by hugsy** [comment]
Correct, the instruction is invalid.
Nonetheless it shouldn't crash. Try again with the latest version (which has hardcoded requirements), it does crash.
