### ISSUE TITLE
Improvement to the requirements.sh

### ISSUE THREAD

**Issue by RafaelRMachado** [hugsy/cemu#7]
Just for the project installation to work easier. It would be a good idea to add the installation of cmake and setupTools to the installation script.

sudo apt-get install cmake
sudo apt-get install python3-setuptools

Thanks 
Rafael

**Comment by hugsy** [comment]
Hi @RafaelRMachado 

See commit 1945054
Using `apt` or `yum` in the file would imply to check whether the distro is Debian, Ubuntu, RedHat whatever, which is too much trouble.
I've added checks to exit cleanly the script if those tools are not found.

Thanks for the feedback.

**Comment by RafaelRMachado** [comment]
Just noticed that there is another dependency. The PyQt5 package

**Comment by hugsy** [comment]
No, it is installed from the file `requirements.txt`.
