### ISSUE TITLE
Random improvement idea list

### ISSUE THREAD

**Issue by hugsy** [hugsy/cemu#8]
### New features for CEMU

To add (in no particular order):
- [x] Add string support (convert "ABCD" -> 0x41424344)
- [x] resizable window
- [x] add new column for Mappings tab to prefill the memory location with the content of a file
- [x] generate valid .s ASM file ready to compile 
- [x] check support on windows
- [x] check support on osx
- [x] improve dependency installer
- [x] add a Python interpreter widget tab
- [x] change memory mapping layout to QTableWidget or grid layout

**Comment by agnosticlines** [comment]
Being able to step backwards would be awesome, as well as clicking on each instruction and viewing the registers at that point in time, I'm not sure how tricky that'll be.

Thanks for your awesome project.

**Comment by hugsy** [comment]
@agnosticlines Unlikely, it would require to keep track of all memory access which would make it hardly manageable. I try to keep this project simple so most can use.

**Comment by hugsy** [comment]
Added Python console widget by commit 01c9c46f83b3e2badb725d8076b3d7b7aa982b85.
