### ISSUE TITLE
Python311 operate error

### ISSUE THREAD

**Issue by QinYaHang** [hugsy/cemu#87]
![image](https://github.com/hugsy/cemu/assets/29395290/74adb9f5-42e8-46e2-86de-a3207ef3c081)

C:\Users\Administrator\Desktop>python -m cemu
[DEBUG] Starting in Debug Mode
[DEBUG] Creating GUI context
[DEBUG] Settings loaded from 'C:\Users\Administrator\.cemu.ini'
[SUCCESS] Loaded plugin 'D:\soft\Python\Python311\Lib\site-packages\cemu\plugins\pyconsole'
[SUCCESS] Loaded plugin 'D:\soft\Python\Python311\Lib\site-packages\cemu\plugins\scratchboard.py'
[DEBUG] Main window initialized
[DEBUG] Emulator state transition: STARTING -> NOT_RUNNING
[INFO] Emulator is now NOT_RUNNING
[DEBUG] Executing 4 callbacks for state NOT_RUNNING
[DEBUG] cemu.ui.registers.method.updateGrid() return None
[DEBUG] cemu.ui.mapping.method.onNotRunningUpdateMemoryMap() return None
[DEBUG] cemu.ui.command.method.onNotRunningUpdateCommandButtons() return None
[DEBUG] cemu.ui.main.method.update_layout_not_running() return None
Traceback (most recent call last):
  File "D:\soft\Python\Python311\Lib\site-packages\cemu\ui\codeeditor.py", line 178, in onUpdateText
    cemu.core.context.emulator.codelines = self.getCleanContent()
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Python\Python311\Lib\site-packages\cemu\ui\codeeditor.py", line 239, in getCleanContent
    lines = parse_syscalls(lines)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Python\Python311\Lib\site-packages\cemu\ui\codeeditor.py", line 210, in parse_syscalls
    syscalls = cemu.core.context.architecture.syscalls
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\soft\Python\Python311\Lib\site-packages\cemu\arch\__init__.py", line 72, in syscalls
    self.__context = getattr(mod, "context")
                     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cemu' has no attribute 'context'

C:\Users\Administrator\Desktop>

**Comment by CeruleanSky** [comment]
I have this exact error on windows 10 64bit on python 3.10.4 as well.

**Comment by hugsy** [comment]
This issue is already fixed, will be part of the next release.

**Comment by ADemonevil** [comment]
same problem，works in july 9
