### ISSUE TITLE
Memory map fails to correctly reset after architecture changed

### ISSUE THREAD

**Issue by YTyyds** [hugsy/cemu#89]
![image](https://github.com/hugsy/cemu/assets/106136496/a0a47500-45ee-42d1-ac2c-ceceb0615dae)
Whenever I try to debug the ARM environment, he blinks back and pops the following error
![image](https://github.com/hugsy/cemu/assets/106136496/216cb613-336e-4980-912a-76882c70fbb1)

\cemu\emulator.py", line 199, in __populate_memory
    self.start_addr = self.sections[0].address
IndexError: list index out of range

**Comment by fxh615** [comment]
the same

**Comment by hugsy** [comment]
Yes, I am aware of the bug but haven't had a chance to work on a fix.
